# Generated by Django 6.0 on 2026-01-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audioTitle', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('language', models.CharField(max_length=100)),
                ('filePath', models.FileField(max_length=500, upload_to='audios/')),
                ('audioImage', models.ImageField(blank=True, max_length=500, null=True, upload_to='audio_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'audios',
                'ordering': ['-created_at'],
            },
        ),
    ]
